name: Build and Deploy to Google Cloud Run

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build-and-deploy:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ' ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/satchel:latest

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy satchel \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/satchel:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated