name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - "release"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ' ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/satchel:latest
        build-args: |
            PROJECT_ID=${{secrets.PROJECT_ID}}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy satchel \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/satchel:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated